import { select } from "@clack/prompts";
import { splitRoute } from "@djs-core/runtime";
import type { CAC } from "cac";
import fs from "fs/promises";
import path from "path";
import pc from "picocolors";
import { banner, PATH_ALIASES } from "../utils/common";
import { autoGenerateConfigTypes } from "../utils/config-type-generator";
import {
	DB_BUNDLE_EXTERNALS,
	projectNeedsDb,
	usesDbInSource,
} from "../utils/db-usage";

declare const Bun: typeof import("bun");

type BuildOptions = {
	path: string;
	outdir: string;
	minify: boolean;
	compile?: boolean;
	bundled?: boolean;
	external?: boolean;
	docker?: boolean;
};

function toPosixPath(p: string): string {
	return p.split(path.sep).join("/");
}

function ensureRelImport(p: string): string {
	return p.startsWith(".") ? p : `./${p}`;
}

function routeFromFile(baseDir: string, absFile: string): string | null {
	const rel = path.relative(baseDir, absFile);
	const relNoExt = rel.replace(/\.ts$/i, "");
	const parts = relNoExt.split(path.sep).filter(Boolean);
	if (parts.length === 0) return null;
	if (parts[parts.length - 1] === "index") parts.pop();
	if (parts.length === 0) return null;
	return parts.join(".");
}

async function listTsFilesRecursive(dir: string): Promise<string[]> {
	try {
		await fs.access(dir);
	} catch {
		return [];
	}

	const out: string[] = [];
	const entries = await fs.readdir(dir, { withFileTypes: true });
	for (const e of entries) {
		const full = path.join(dir, e.name);
		if (e.isDirectory()) {
			out.push(...(await listTsFilesRecursive(full)));
		} else if (
			e.isFile() &&
			e.name.endsWith(".ts") &&
			!e.name.endsWith(".d.ts") &&
			!e.name.endsWith(".test.ts")
		) {
			out.push(full);
		}
	}
	return out;
}

function makeVar(
	prefix: "cmd" | "btn" | "ctx" | "sel" | "mod" | "evt" | "cron",
	route: string,
): string {
	const safe = route.replace(/[^a-zA-Z0-9_]+/g, "_");
	return `${prefix}_${safe}`;
}

type RouteEntry = { route: string; varName: string };

function processFiles(
	files: string[],
	genDir: string,
	prefix: "cmd" | "btn" | "ctx" | "sel" | "mod" | "evt" | "cron",
	getRoute: (f: string) => string | null,
): { importLines: string[]; entries: RouteEntry[] } {
	const importLines: string[] = [];
	const entries: RouteEntry[] = [];
	for (const f of files) {
		const route = getRoute(f);
		if (!route) continue;
		const varName = makeVar(prefix, route);
		const rel = ensureRelImport(toPosixPath(path.relative(genDir, f)));
		importLines.push(`import ${varName} from "${rel}";`);
		entries.push({ route, varName });
	}
	entries.sort((a, b) => a.route.localeCompare(b.route));
	return { importLines, entries };
}

export function buildGeneratedEntry(opts: {
	genDir: string;
	commandsDir: string;
	buttonsDir: string;
	contextsDir: string;
	selectsDir: string;
	modalsDir: string;
	commandFiles: string[];
	buttonFiles: string[];
	contextFiles: string[];
	selectFiles: string[];
	modalFiles: string[];
	eventFiles: string[];
	cronFiles: string[];
	hasCronEnabled: boolean;
	hasUserConfigEnabled: boolean;
	hasBundleEnabled: boolean;
	hasDbEnabled: boolean;
}): string {
	const {
		genDir,
		commandsDir,
		buttonsDir,
		contextsDir,
		selectsDir,
		modalsDir,
	} = opts;

	const cmds = processFiles(opts.commandFiles, genDir, "cmd", (f) =>
		routeFromFile(commandsDir, f),
	);
	const btns = processFiles(opts.buttonFiles, genDir, "btn", (f) =>
		routeFromFile(buttonsDir, f),
	);
	const ctxs = processFiles(opts.contextFiles, genDir, "ctx", (f) =>
		routeFromFile(contextsDir, f),
	);
	const sels = processFiles(opts.selectFiles, genDir, "sel", (f) =>
		routeFromFile(selectsDir, f),
	);
	const mods = processFiles(opts.modalFiles, genDir, "mod", (f) =>
		routeFromFile(modalsDir, f),
	);
	const evts = processFiles(opts.eventFiles, genDir, "evt", (f) =>
		path.basename(f, ".ts"),
	);
	const crons = processFiles(opts.cronFiles, genDir, "cron", (f) =>
		path.basename(f, ".ts"),
	);

	const allImports = [
		...cmds.importLines,
		...btns.importLines,
		...ctxs.importLines,
		...sels.importLines,
		...mods.importLines,
		...evts.importLines,
		...crons.importLines,
	];

	const sortedCmds = cmds.entries;
	const sortedBtns = btns.entries;
	const sortedCtxs = ctxs.entries;
	const sortedSels = sels.entries;
	const sortedMods = mods.entries;
	const sortedEvts = evts.entries;
	const sortedCrons = crons.entries;

	return `/* Auto-generated by djs-core. Do not edit manually. */
import path from "node:path";
import config from "../djs.config.ts";
import { DjsClient, type Route } from "@djs-core/runtime";
import { Events } from "discord.js";
${
	opts.hasDbEnabled
		? 'import { prepareClientDb } from "@djs-core/runtime/prepareDb";'
		: ""
}
${
	opts.hasUserConfigEnabled
		? 'import type { UserConfig } from "./config.types.ts";'
		: ""
}
${
	opts.hasUserConfigEnabled && opts.hasBundleEnabled
		? 'import userConfigData from "../config.json" with { type: "json" };'
		: ""
}

${allImports.join("\n")}

function assertConfig(x: unknown): asserts x is { token: string; servers: string[] } {
  if (!x || typeof x !== "object") throw new Error("Invalid config: expected an object");
  const obj = x as any;
  if (typeof obj.token !== "string" || obj.token.length === 0) throw new Error("Invalid config: token is missing");
  if (!Array.isArray(obj.servers)) throw new Error("Invalid config: servers must be an array");
}

async function main() {
  assertConfig(config);

  const commands: Route[] = [
${sortedCmds
	.map(
		(c) => `    { route: ${JSON.stringify(c.route)}, command: ${c.varName} },`,
	)
	.join("\n")}
  ];

  const buttons = [
${sortedBtns.map((b) => `    ${b.varName},`).join("\n")}
  ];

${sortedBtns
	.map((b) => `  ${b.varName}.setCustomId(${JSON.stringify(b.route)});`)
	.join("\n")}

  const contextMenus = [
${sortedCtxs.map((c) => `    ${c.varName},`).join("\n")}
  ];

${sortedCtxs
	.map((c) => {
		const parts = splitRoute(c.route);
		const leaf = parts[parts.length - 1];
		return `  ${c.varName}.setName(${JSON.stringify(leaf)});`;
	})
	.join("\n")}

  const selectMenus = [
${sortedSels.map((s) => `    ${s.varName},`).join("\n")}
  ];

${sortedSels
	.map((s) => `  ${s.varName}.setCustomId(${JSON.stringify(s.route)});`)
	.join("\n")}

  const modals = [
${sortedMods.map((m) => `    ${m.varName},`).join("\n")}
  ];

${sortedMods
	.map((m) => `  ${m.varName}.setCustomId(${JSON.stringify(m.route)});`)
	.join("\n")}

  const events = {
${sortedEvts
	.map((e) => `    ${JSON.stringify(e.route)}: ${e.varName},`)
	.join("\n")}
  };

${
	opts.hasCronEnabled && sortedCrons.length > 0
		? `  const tasks = new Map([
${sortedCrons
	.map((c) => `    [${JSON.stringify(c.route)}, ${c.varName}],`)
	.join("\n")}
  ]);`
		: ""
}

  // Load user config if enabled. The type assertion is safe because:
  // 1. The config.json is parsed and validated at build time
  // 2. The UserConfig type is auto-generated from config.json structure
  // 3. Any runtime mismatch will be caught during bot initialization
${
	opts.hasUserConfigEnabled
		? opts.hasBundleEnabled
			? "  const client = new DjsClient<UserConfig>({ djsConfig: config, userConfig: userConfigData as UserConfig });"
			: `  let userConfigData: UserConfig | undefined;
  try {
    const configPath = path.join(process.cwd(), "config.json");
    const configFile = Bun.file(configPath);
    if (await configFile.exists()) {
      userConfigData = await configFile.json();
    } else {
      console.warn("⚠️  config.json not found at runtime");
    }
  } catch (e) {
    console.error("❌ Failed to load config.json:", e);
  }
  const client = new DjsClient<UserConfig>({ djsConfig: config, userConfig: userConfigData as UserConfig });`
		: "  const client = new DjsClient({ djsConfig: config });"
}

${
	opts.hasDbEnabled
		? "  if (config.db) {\n    client.registerDbInit(prepareClientDb(client, config.db));\n  }\n"
		: ""
}

  await client.waitForReady();

  client.eventsHandler.set(events);

  client.once(Events.ClientReady, async () => {
    client.commandsHandler.set(commands);
    client.contextMenusHandler.set(contextMenus);
    client.applicationCommandHandler.setCommands(commands);
    client.applicationCommandHandler.setContextMenus(
      client.contextMenusHandler.getContextMenus(),
    );
    await client.applicationCommandHandler.sync();
    client.buttonsHandler.set(buttons);
    client.selectMenusHandler.set(selectMenus);
    client.modalsHandler.set(modals);
${
	opts.hasCronEnabled && sortedCrons.length > 0
		? "    if (config.experimental?.cron && tasks.size > 0) {\n      client.cronHandler.set(tasks);\n    }"
		: ""
}
    console.log(\`✅ Bot online (\${client.user?.tag ?? "unknown"})\`);
  });

  process.on("SIGINT", async () => {
    console.log("\\nShutting down...");
    await client.destroy();
    process.exit(0);
  });

  process.on("SIGTERM", async () => {
    console.log("\\nShutting down...");
    await client.destroy();
    process.exit(0);
  });

  await client.login(config.token);
}

main();
`;
}

async function copyDirRecursive(src: string, dest: string): Promise<void> {
	await fs.mkdir(dest, { recursive: true });
	const entries = await fs.readdir(src, { withFileTypes: true });
	for (const entry of entries) {
		const srcPath = path.join(src, entry.name);
		const destPath = path.join(dest, entry.name);
		if (entry.isDirectory()) {
			await copyDirRecursive(srcPath, destPath);
		} else if (entry.isFile()) {
			await fs.copyFile(srcPath, destPath);
		}
	}
}

async function copyDbMigrationsToDist(
	botRoot: string,
	outdirAbs: string,
	config: import("@djs-core/runtime").Config,
): Promise<boolean> {
	if (!config.db) return false;

	const migrationsSrc = path.join(botRoot, "db", "migrations");
	const migrationsDest = path.join(outdirAbs, "db", "migrations");

	try {
		await fs.access(migrationsSrc);
		await copyDirRecursive(migrationsSrc, migrationsDest);
		console.log(
			`${pc.green("✓")}  db/migrations copied to ${pc.bold("dist/db/migrations/")}`,
		);
		return true;
	} catch {
		if (config.db.autoMigrate) {
			console.warn(
				pc.yellow(
					"⚠️  autoMigrate enabled but db/migrations not found — run djs-core db generate",
				),
			);
		}
		return false;
	}
}

export function generateDockerfileContent(options: {
	includeMigrations: boolean;
}): string {
	const lines = [
		"FROM oven/bun:alpine",
		"WORKDIR /app",
		"COPY --chown=bun:bun index.js .",
	];

	if (options.includeMigrations) {
		lines.push("COPY --chown=bun:bun db/migrations ./db/migrations");
	}

	lines.push(
		"USER bun",
		"HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \\",
		'  CMD test "$(cat /proc/1/comm 2>/dev/null)" = bun || exit 1',
		'CMD ["bun", "index.js"]',
		"",
	);

	return lines.join("\n");
}

export function registerBuildCommand(cli: CAC) {
	cli
		.command("build", "Build production bundle")
		.option("-p, --path <path>", "Custom project path", { default: "." })
		.option(
			"-o, --outdir <outdir>",
			"Output directory (relative to project root)",
			{ default: "dist" },
		)
		.option("--no-minify", "Disable minification")
		.option("--bundled", "Bun (bundled)")
		.option("--external", "Bun (external deps)")
		.option("-c, --compile", "Compile to a standalone binary")
		.option("--docker", "Bun bundle + Dockerfile for container deployment")
		.action(async (options: BuildOptions) => {
			console.log(banner);

			const botRoot = path.resolve(process.cwd(), options.path);
			const genDir = path.join(botRoot, ".djscore");
			const entryPath = path.join(genDir, "index.ts");

			const commandsDir = path.join(
				botRoot,
				PATH_ALIASES.interactions,
				"commands",
			);
			const buttonsDir = path.join(botRoot, PATH_ALIASES.components, "buttons");
			const contextsDir = path.join(
				botRoot,
				PATH_ALIASES.interactions,
				"contexts",
			);
			const selectsDir = path.join(botRoot, PATH_ALIASES.components, "selects");
			const modalsDir = path.join(botRoot, PATH_ALIASES.components, "modals");
			const eventsDir = path.join(botRoot, PATH_ALIASES.events);
			const cronDir = path.join(botRoot, "src", "cron");

			console.log(`${pc.cyan("ℹ")}  Project: ${pc.bold(botRoot)}`);
			console.log(`${pc.cyan("ℹ")}  Generating: ${pc.bold(entryPath)}\n`);

			await fs.mkdir(genDir, { recursive: true });

			const commandFiles = await listTsFilesRecursive(commandsDir);
			const buttonFiles = await listTsFilesRecursive(buttonsDir);
			const contextFiles = await listTsFilesRecursive(contextsDir);
			const selectFiles = await listTsFilesRecursive(selectsDir);
			const modalFiles = await listTsFilesRecursive(modalsDir);
			const eventFiles = await listTsFilesRecursive(eventsDir);
			const cronFiles = await listTsFilesRecursive(cronDir);

			const configModule = await import(path.join(botRoot, "djs.config.ts"));
			const config = configModule.default as import("@djs-core/runtime").Config;
			const hasCronEnabled = config.experimental?.cron === true;
			const hasUserConfigEnabled = config.experimental?.userConfig === true;
			const hasBundleEnabled = config.experimental?.bundle === true;

			const hasDbEnabled = Boolean(config.db);
			const needsDb = projectNeedsDb(botRoot, hasDbEnabled);

			if (!hasDbEnabled && usesDbInSource(botRoot)) {
				console.warn(
					pc.yellow(
						"⚠️  src/ uses client.db or @djs-core/db but djs.config.ts has no db: block",
					),
				);
			}

			// Auto-generate config types
			await autoGenerateConfigTypes(botRoot, config, true);

			const code = buildGeneratedEntry({
				genDir,
				commandsDir,
				buttonsDir,
				contextsDir,
				selectsDir,
				modalsDir,
				commandFiles,
				buttonFiles,
				contextFiles,
				selectFiles,
				modalFiles,
				eventFiles,
				cronFiles,
				hasCronEnabled,
				hasUserConfigEnabled,
				hasBundleEnabled,
				hasDbEnabled,
			});

			await fs.writeFile(entryPath, code, "utf8");

			let buildType: string | null = null;
			const buildFlagConflict = () => {
				console.error(
					pc.red(
						"❌ Cannot combine build flags --bundled/--external/--compile/--docker",
					),
				);
				process.exit(1);
			};

			if (options.compile) buildType = "compile";
			if (options.bundled) {
				if (buildType) buildFlagConflict();
				buildType = "bun";
			}
			if (options.external) {
				if (buildType) buildFlagConflict();
				buildType = "bun-external";
			}
			if (options.docker) {
				if (buildType) buildFlagConflict();
				buildType = "docker";
			}

			if (!buildType) {
				buildType = (await select({
					message: "Select build type:",
					options: [
						{ value: "bun", label: "Bun (bundled)" },
						{ value: "bun-external", label: "Bun (external deps)" },
						{ value: "compile", label: "Compile (Native binary, ~90MB)" },
						{ value: "docker", label: "Docker" },
					],
				})) as string;
			}

			if (!buildType) {
				console.log(pc.red("❌ Build cancelled"));
				process.exit(1);
			}

			const outdirAbs = path.resolve(botRoot, options.outdir);

			try {
				await fs.rm(outdirAbs, { recursive: true, force: true });
			} catch {
				// Ignore if directory doesn't exist
			}

			await fs.mkdir(outdirAbs, { recursive: true });

			let migrationsCopied = false;

			if (hasUserConfigEnabled && !hasBundleEnabled) {
				const configJsonPath = path.join(botRoot, "config.json");
				const outConfigJsonPath = path.join(outdirAbs, "config.json");
				try {
					await fs.copyFile(configJsonPath, outConfigJsonPath);
					console.log(
						`${pc.green("✓")}  config.json copied to ${pc.bold("dist/")}`,
					);
				} catch (_e) {
					console.warn(pc.yellow("⚠️  Could not copy config.json to dist/"));
				}
			}

			if (needsDb) {
				migrationsCopied = await copyDbMigrationsToDist(
					botRoot,
					outdirAbs,
					config,
				);
			}

			if (buildType === "compile") {
				const exeName = process.platform === "win32" ? "bot.exe" : "bot";
				const outputPath = path.join(outdirAbs, exeName);

				console.log(`${pc.cyan("ℹ")}  Compiling native binary...`);

				const buildArgs = [
					"build",
					entryPath,
					"--compile",
					"--outfile",
					outputPath,
				];

				if (options.minify !== false) {
					buildArgs.push("--minify");
				}

				const proc = Bun.spawn(["bun", ...buildArgs], {
					stdout: "inherit",
					stderr: "inherit",
				});

				const exitCode = await proc.exited;

				if (exitCode !== 0) {
					console.error(pc.red("\n❌ Compilation failed"));
					process.exit(1);
				}

				const stats = await fs.stat(outputPath);
				const sizeMB = (stats.size / (1024 * 1024)).toFixed(2);

				console.log(
					pc.green("\n✓") +
						`  Build success: ${pc.bold(exeName)} (${sizeMB} MB)`,
				);
				console.log(pc.dim(`  - ${outputPath}`));
				console.log(
					pc.dim(`\nTip: run your bot with: ./${options.outdir}/${exeName}\n`),
				);
				process.exit(0);
			}

			const botPackageJsonPath = path.join(botRoot, "package.json");
			let externalDeps: string[] = [];

			if (buildType === "bun-external") {
				try {
					const botPackageJson = JSON.parse(
						await fs.readFile(botPackageJsonPath, "utf-8"),
					);
					externalDeps = [
						...Object.keys(botPackageJson.dependencies || {}),
						...Object.keys(botPackageJson.peerDependencies || {}),
						"discord.js",
					].filter((d) => d !== "@djs-core/runtime");
					if (needsDb) {
						externalDeps.push(...DB_BUNDLE_EXTERNALS);
					}
				} catch (_e) {
					console.warn(
						pc.yellow(
							"⚠️  Could not read package.json, using default externals",
						),
					);
					externalDeps = ["discord.js"];
				}
			}

			const result = await Bun.build({
				entrypoints: [entryPath],
				outdir: outdirAbs,
				target: "bun",
				minify: !!options.minify,
				splitting: false,
				sourcemap: "none",
				external: buildType === "bun-external" ? externalDeps : [],
			});

			if (!result.success) {
				console.error(pc.red("❌ Build failed"));
				for (const log of result.logs) console.error(log);
				process.exit(1);
			}

			const outputs = result.outputs.map((o: { path: string }) => o.path);
			const outputFile = path.join(outdirAbs, "index.js");
			const stats = await fs.stat(outputFile);
			const sizeKB = (stats.size / 1024).toFixed(2);
			const sizeMB = (stats.size / (1024 * 1024)).toFixed(2);
			const sizeDisplay =
				stats.size > 1024 * 1024 ? `${sizeMB} MB` : `${sizeKB} KB`;

			const totalSourceFiles =
				commandFiles.length +
				buttonFiles.length +
				contextFiles.length +
				selectFiles.length +
				modalFiles.length +
				eventFiles.length;

			console.log(
				pc.green("✓") +
					`  Build success (${totalSourceFiles} file${
						totalSourceFiles === 1 ? "" : "s"
					} → ${outputs.length} output${
						outputs.length === 1 ? "" : "s"
					}, ${sizeDisplay})`,
			);
			for (const p of outputs) console.log(pc.dim(`  - ${p}`));

			if (buildType === "docker") {
				const dockerfileContent = generateDockerfileContent({
					includeMigrations: migrationsCopied,
				});
				const dockerfilePath = path.join(outdirAbs, "Dockerfile");
				await fs.writeFile(dockerfilePath, dockerfileContent, "utf8");
				console.log(
					`${pc.green("✓")}  Dockerfile created: ${pc.bold("Dockerfile")}`,
				);
				console.log(
					pc.dim(
						`\nTip: build with: docker build -t my-bot ${options.outdir}\n`,
					),
				);
			} else if (buildType === "bun-external") {
				try {
					const botPackageJson = JSON.parse(
						await fs.readFile(botPackageJsonPath, "utf-8"),
					);
					const distPackageJson = {
						name: botPackageJson.name || "bot",
						version: botPackageJson.version || "1.0.0",
						type: "module",
						scripts: {
							start: "bun index.js",
						},
						dependencies: botPackageJson.dependencies || {},
						peerDependencies: botPackageJson.peerDependencies || {},
					};

					const distPackageJsonPath = path.join(outdirAbs, "package.json");
					await fs.writeFile(
						distPackageJsonPath,
						JSON.stringify(distPackageJson, null, 2),
						"utf8",
					);
					console.log(
						pc.green("✓") +
							`  package.json created: ${pc.bold("package.json")}`,
					);
					console.log(
						pc.dim(
							`\nTip: install deps then run: cd ${options.outdir} && bun install && bun start\n`,
						),
					);
				} catch (_e) {
					console.warn(pc.yellow("⚠️  Could not generate package.json"));
					console.log(
						pc.dim(
							`\nTip: run with: bun ${path.join(options.outdir, "index.js")}\n`,
						),
					);
				}
			} else {
				console.log(
					pc.dim(
						`\nTip: run with: bun ${path.join(options.outdir, "index.js")}\n`,
					),
				);
			}

			process.exit(0);
		});
}
