import { readdirSync, existsSync, mkdirSync, rmSync, renameSync, writeFileSync, statSync } from "fs";
import { resolve, extname, relative } from "path";
import { build as tsupBuild } from "tsup";

function collectFiles(dir: string, matcher: (file: string) => boolean, acc: string[]) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      collectFiles(full, matcher, acc);
    } else if (entry.isFile() && matcher(full)) {
      acc.push(full);
    }
  }
}

export async function runBuild(projectRoot: string, opts: { docker?: boolean; js?: boolean } = {}) {
  const root = resolve(process.cwd(), projectRoot ?? ".");

  const cmdDir = resolve(root, "src/commands");
  const evtDir = resolve(root, "src/events");
  const validExt = [".ts", ".js", ".mjs", ".cjs"];
  const commandFiles: string[] = [];
  const eventFiles: string[] = [];
  if (existsSync(cmdDir)) collectFiles(cmdDir, (f) => validExt.includes(extname(f)), commandFiles);
  if (existsSync(evtDir)) collectFiles(evtDir, (f) => validExt.includes(extname(f)), eventFiles);

  const genDir = resolve(root, ".djs-generated");
  mkdirSync(genDir, { recursive: true });
  const entryPath = resolve(genDir, "index.ts");

  const importLines: string[] = [];
  const commandVars: string[] = [];
  const eventVars: string[] = [];

  commandFiles.forEach((file, idx) => {
    const rel = "../" + relative(root, file).replace(/\\/g, "/");
    const varName = `Cmd${idx}`;
    importLines.push(`import ${varName} from "${rel}";`);
    commandVars.push(varName);
  });

  eventFiles.forEach((file, idx) => {
    const rel = "../" + relative(root, file).replace(/\\/g, "/");
    const varName = `Evt${idx}`;
    importLines.push(`import ${varName} from "${rel}";`);
    eventVars.push(`new ${varName}()`);
  });

  let cfgImport = "";
  if (existsSync(resolve(root, "djsconfig.ts"))) {
    cfgImport = `import config from "../djsconfig.ts";`;
  } else if (existsSync(resolve(root, "djsconfig.js"))) {
    cfgImport = `import config from "../djsconfig.js";`;
  } else {
    throw new Error("djsconfig.ts/js not found in project root");
  }

  const handlerContent = `import { Client } from "discord.js";
${cfgImport}
${importLines.join("\n")}
import { registerHandlers } from "djs-core";

const client = new Client({ intents: config.intents ?? [] });

registerHandlers({
  client,
  commands: [${commandVars.join(", ")}],
  events: [${eventVars.join(", ")}],
});

client.login(config.token);
`;

  await Bun.write(entryPath, handlerContent);

  const distDir = resolve(root, "dist");
  const entryGlobs = [entryPath.replace(/\\/g, "/")];
  
  await tsupBuild({
    entry: entryGlobs,
    format: "esm",
    clean: true,
    minify: true,
    outDir: distDir,
    target: "es2020",
    treeshake: true,
    dts: false,
    silent: true,
    external: ["discord.js"],
  });

  try {
    const userPkgPath = resolve(root, "package.json");
    const userPkg = JSON.parse(await Bun.file(userPkgPath).text());
    const runtimeCmd = opts.js ? "node" : "bun";

    const prodPkg = {
      name: userPkg.name ?? "my-bot",
      version: userPkg.version ?? "1.0.0",
      type: "module",
      main: "index.js",
      dependencies: userPkg.dependencies ?? {},
      scripts: {
        ...Object.fromEntries(
          Object.entries(userPkg.scripts ?? {}).filter(([k]) => k !== "build")
        ),
        start: `${runtimeCmd} index.js`
      },
    };
    writeFileSync(resolve(distDir, "package.json"), JSON.stringify(prodPkg, null, 2));

    if (opts.docker) {
      const dockerFile = `# ---- DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING ----\nFROM oven/bun:alpine\nWORKDIR /app\nCOPY . .\nRUN bun i --production\nCMD [\"bun\", \"start\"]\n`;
      writeFileSync(resolve(distDir, "Dockerfile"), dockerFile);
    }
  } catch (e) {
    console.warn("⚠️  Failed to copy dependencies to dist/package.json", e);
  }

  rmSync(genDir, { recursive: true, force: true });

  const finalFile = resolve(distDir, "index.js");
  const sizeKB = (statSync(finalFile).size / 1024).toFixed(2);
  const totalInputs = commandFiles.length + eventFiles.length;

  const runtimeLabel = opts.js ? "Node.js" : "Bun";

  console.log(`✅ Build complete: ${totalInputs} fichier(s) source compilé(s) → dist/index.js (${sizeKB} KB) [runtime: ${runtimeLabel}].${opts.docker ? " Dockerfile généré." : ""}`);
} 