name: Lint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  autofix:
    runs-on: ubuntu-latest
    concurrency:
      group: lint-${{ github.ref_name }}
      cancel-in-progress: true

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies for linting
        run: pnpm install --no-frozen-lockfile

      - name: Run ESLint
        run: pnpm run lint

      - name: Run Prettier
        run: pnpm run pretty

      - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
