name: Release and Publish NPM

on:
  workflow_run:
    workflows:
      - "Build and Test"
    types:
      - completed
jobs:
  release:
    name: Build and Publish
    runs-on: ubuntu-latest

    if: startsWith(github.event.workflow_run.head_commit.message, 'v')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm build

      - name: Create GitHub Release (Draft)
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "${{ github.ref_name }}"
          draft: true
          body: |
            ### Notes de cette version
            Ajoute ici les détails que tu veux compléter manuellement.

      - name: Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: NPM Publish
        run: |
          if [ -d "dist" ]; then
             cd dist
             npm publish
          else
             echo "Le dossier 'dist' n'existe pas."
             exit 1
          fi
