name: Auto Release and Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm build

      - name: Pack for GitHub Releases
        run: cd dist/ && pnpm pack

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            dist/*.tgz
          body: |
            ### Notes de cette version
            Ajoute ici les détails que tu veux compléter manuellement.
          
            
      # - name: Authenticate with NPM
      #   run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # - name: NPM Publish
      #   run: |
      #     if [ -d "dist" ]; then
      #        cd dist
      #        npm publish
      #     else
      #        echo "Le dossier 'dist' n'existe pas."
      #        exit 1
      #     fi
